/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package taproim_cmsc495;

import java.awt.Color;

/**
 *
 * @author Brandon
 */
public class Display_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Display_GUI
     */
    public Display_GUI() {
        this.setTitle("                               "
                + "                                         "
                + "                      TAPRO-IM SYSTEMS");
        //getContentPane().setBackground(Color.GRAY);
        initComponents();
        newOrderPanel.setVisible(false);
        updateInventoryPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newShipmentButton = new javax.swing.JButton();
        updateCustomerButton = new javax.swing.JButton();
        updateInventoryButton = new javax.swing.JButton();
        updateShipmentButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tableLabel = new javax.swing.JLabel();
        viewInventoryTableButton = new javax.swing.JButton();
        viewShipmentTableButton = new javax.swing.JButton();
        viewCustomerTableButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        newOrderPanel = new javax.swing.JPanel();
        customerNameLabel = new javax.swing.JLabel();
        customerNameField = new javax.swing.JTextField();
        customerIDLabel = new javax.swing.JLabel();
        customerIDField = new javax.swing.JTextField();
        customerAddressButton = new javax.swing.JLabel();
        customerAddressField = new javax.swing.JTextField();
        itemIDButton = new javax.swing.JLabel();
        itemIDField = new javax.swing.JTextField();
        itemCountButton = new javax.swing.JLabel();
        itemCountField = new javax.swing.JTextField();
        itemWeightButton = new javax.swing.JLabel();
        itemWeightField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        clearAllButton = new javax.swing.JButton();
        notificationLabel = new javax.swing.JLabel();
        destinationLabel = new javax.swing.JLabel();
        destinationField = new javax.swing.JTextField();
        customerEmailLabel = new javax.swing.JLabel();
        customerEmailField = new javax.swing.JTextField();
        shipmentIDLabel = new javax.swing.JLabel();
        shipmentIDField = new javax.swing.JTextField();
        updateInventoryPanel = new javax.swing.JPanel();
        itemIDUpdateLabel = new javax.swing.JLabel();
        itemWeightUpdateLabel = new javax.swing.JLabel();
        itemStockLevelUpdateLabel = new javax.swing.JLabel();
        itemDescriptionUpdateLabel = new javax.swing.JLabel();
        itemIDUpdateField = new javax.swing.JTextField();
        itemWeightUpdateField = new javax.swing.JTextField();
        itemStockLevelUpdateField = new javax.swing.JTextField();
        itemDescriptionUpdateField = new javax.swing.JTextField();
        updateInventoryButtonFinal = new javax.swing.JButton();
        deleteInventoryButton = new javax.swing.JButton();
        notificationUpdateInventoryLabel = new javax.swing.JLabel();
        searchInventoryButton = new javax.swing.JButton();
        updateCustomerPanel = new javax.swing.JPanel();
        customerIDCustomerUpdateLabel = new javax.swing.JLabel();
        customerIDCustomerUpdateField = new javax.swing.JTextField();
        customerNameUpdateLabel = new javax.swing.JLabel();
        customerAddressUpdateLabel = new javax.swing.JLabel();
        customerNameUpdateField = new javax.swing.JTextField();
        customerAddressUpdateField = new javax.swing.JTextField();
        updateCustomerButtonFinal = new javax.swing.JButton();
        notificationCustomerUpdateLabel = new javax.swing.JLabel();
        customerEmailUpdateLabel = new javax.swing.JLabel();
        customerEmailUpdateField = new javax.swing.JTextField();
        searchUpdateCustomerButton = new javax.swing.JButton();
        deleteCustomerButton = new javax.swing.JButton();
        updateShipmentPanel = new javax.swing.JPanel();
        customerIDShippingUpdateLabel = new javax.swing.JLabel();
        customerIDShippingUpdateField = new javax.swing.JTextField();
        currentCityShippingUpdateLabel = new javax.swing.JLabel();
        currentCityShippingUpdateField = new javax.swing.JTextField();
        shippingDateShippingUpdateLabel = new javax.swing.JLabel();
        shippingDateShippingUpdateField = new javax.swing.JTextField();
        updateShippingButtonFinal = new javax.swing.JButton();
        invalidShippingUpdateLabel = new javax.swing.JLabel();
        arrivalDateShippingUpdateLabel = new javax.swing.JLabel();
        arrivalDateShippingUpdateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newShipmentButton.setText("NEW SHIPMENT");
        newShipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newShipmentButtonActionPerformed(evt);
            }
        });

        updateCustomerButton.setText("UPDATE CUSTOMER");
        updateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonActionPerformed(evt);
            }
        });

        updateInventoryButton.setText("UPDATE INVENTORY");
        updateInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInventoryButtonActionPerformed(evt);
            }
        });

        updateShipmentButton.setText("UPDATE SHIPMENT");
        updateShipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShipmentButtonActionPerformed(evt);
            }
        });

        tablePanel.setBackground(new java.awt.Color(204, 204, 204));
        tablePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        tableLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tableLabel.setText("      TABLE DISPLAY");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(tableLabel)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        viewInventoryTableButton.setText("VIEW INVENTORY TABLE");
        viewInventoryTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInventoryTableButtonActionPerformed(evt);
            }
        });

        viewShipmentTableButton.setText("VIEW SHIPMENT TABLE");
        viewShipmentTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewShipmentTableButtonActionPerformed(evt);
            }
        });

        viewCustomerTableButton.setText("VIEW CUSTOMER TABLE");
        viewCustomerTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerTableButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("LOG OUT");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        newOrderPanel.setEnabled(false);

        customerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerNameLabel.setText("Customer Name:");

        customerIDLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerIDLabel.setText("Customer ID:");

        customerAddressButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerAddressButton.setText("Customer Address:");

        itemIDButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemIDButton.setText("Item ID Number:");

        itemCountButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemCountButton.setText("Item Count:");

        itemWeightButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemWeightButton.setText("Item Weight:");

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        clearAllButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        clearAllButton.setText("CLEAR ALL");
        clearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButtonActionPerformed(evt);
            }
        });

        notificationLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        notificationLabel.setForeground(new java.awt.Color(102, 0, 0));

        destinationLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        destinationLabel.setText("Destination:");

        customerEmailLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerEmailLabel.setText("Customer Email:");

        shipmentIDLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        shipmentIDLabel.setText("Shipment ID:");

        javax.swing.GroupLayout newOrderPanelLayout = new javax.swing.GroupLayout(newOrderPanel);
        newOrderPanel.setLayout(newOrderPanelLayout);
        newOrderPanelLayout.setHorizontalGroup(
            newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(shipmentIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destinationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemWeightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemIDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerAddressButton, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(customerIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newOrderPanelLayout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(customerNameField)
                    .addComponent(customerIDField)
                    .addComponent(customerAddressField)
                    .addComponent(itemIDField)
                    .addComponent(itemCountField)
                    .addComponent(destinationField)
                    .addComponent(customerEmailField)
                    .addComponent(itemWeightField)
                    .addComponent(shipmentIDField))
                .addContainerGap())
        );
        newOrderPanelLayout.setVerticalGroup(
            newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerAddressButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerEmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemIDButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemWeightButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemCountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shipmentIDLabel)
                    .addComponent(shipmentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(notificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jLayeredPane1.add(newOrderPanel);
        newOrderPanel.setBounds(10, 0, 710, 340);

        itemIDUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemIDUpdateLabel.setText("Item ID:");

        itemWeightUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemWeightUpdateLabel.setText("Item Weight:");

        itemStockLevelUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemStockLevelUpdateLabel.setText("Item Stock Level:");

        itemDescriptionUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemDescriptionUpdateLabel.setText("Item Description:");

        itemWeightUpdateField.setEnabled(false);

        itemStockLevelUpdateField.setEnabled(false);

        itemDescriptionUpdateField.setEnabled(false);

        updateInventoryButtonFinal.setText("UPDATE");
        updateInventoryButtonFinal.setEnabled(false);
        updateInventoryButtonFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInventoryButtonFinalActionPerformed(evt);
            }
        });

        deleteInventoryButton.setText("DELETE");
        deleteInventoryButton.setEnabled(false);
        deleteInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInventoryButtonActionPerformed(evt);
            }
        });

        notificationUpdateInventoryLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        notificationUpdateInventoryLabel.setForeground(new java.awt.Color(153, 0, 0));

        searchInventoryButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        searchInventoryButton.setText("SEARCH");
        searchInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInventoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateInventoryPanelLayout = new javax.swing.GroupLayout(updateInventoryPanel);
        updateInventoryPanel.setLayout(updateInventoryPanelLayout);
        updateInventoryPanelLayout.setHorizontalGroup(
            updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateInventoryPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemIDUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(itemWeightUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemStockLevelUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemDescriptionUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemIDUpdateField)
                    .addComponent(itemStockLevelUpdateField)
                    .addComponent(itemDescriptionUpdateField)
                    .addGroup(updateInventoryPanelLayout.createSequentialGroup()
                        .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchInventoryButton)
                            .addGroup(updateInventoryPanelLayout.createSequentialGroup()
                                .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateInventoryButtonFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notificationUpdateInventoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(itemWeightUpdateField))
                .addContainerGap())
        );
        updateInventoryPanelLayout.setVerticalGroup(
            updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateInventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemIDUpdateLabel)
                    .addComponent(itemIDUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateInventoryPanelLayout.createSequentialGroup()
                        .addComponent(searchInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateInventoryPanelLayout.createSequentialGroup()
                        .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemWeightUpdateLabel)
                            .addComponent(itemWeightUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemStockLevelUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemStockLevelUpdateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemDescriptionUpdateLabel)
                    .addComponent(itemDescriptionUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(updateInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(notificationUpdateInventoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateInventoryButtonFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteInventoryButton)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jLayeredPane1.add(updateInventoryPanel);
        updateInventoryPanel.setBounds(0, 0, 730, 340);

        customerIDCustomerUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerIDCustomerUpdateLabel.setText("Customer ID:");

        customerNameUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerNameUpdateLabel.setText("Customer Name:");

        customerAddressUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerAddressUpdateLabel.setText("Customer Address:");

        customerNameUpdateField.setEnabled(false);

        customerAddressUpdateField.setEnabled(false);

        updateCustomerButtonFinal.setText("UPDATE");
        updateCustomerButtonFinal.setEnabled(false);
        updateCustomerButtonFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonFinalActionPerformed(evt);
            }
        });

        notificationCustomerUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        notificationCustomerUpdateLabel.setForeground(new java.awt.Color(153, 0, 0));

        customerEmailUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerEmailUpdateLabel.setText("Customer Email:");

        customerEmailUpdateField.setEnabled(false);

        searchUpdateCustomerButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        searchUpdateCustomerButton.setText("SEARCH");
        searchUpdateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUpdateCustomerButtonActionPerformed(evt);
            }
        });

        deleteCustomerButton.setText("DELETE");
        deleteCustomerButton.setEnabled(false);
        deleteCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateCustomerPanelLayout = new javax.swing.GroupLayout(updateCustomerPanel);
        updateCustomerPanel.setLayout(updateCustomerPanelLayout);
        updateCustomerPanelLayout.setHorizontalGroup(
            updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerEmailUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerAddressUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(customerNameUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerIDCustomerUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                        .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameUpdateField)
                            .addComponent(customerAddressUpdateField)
                            .addComponent(customerEmailUpdateField)
                            .addComponent(customerIDCustomerUpdateField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                                .addComponent(updateCustomerButtonFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(notificationCustomerUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                        .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchUpdateCustomerButton)
                            .addComponent(deleteCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        updateCustomerPanelLayout.setVerticalGroup(
            updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDCustomerUpdateLabel)
                    .addComponent(customerIDCustomerUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                        .addComponent(searchUpdateCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerNameUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customerNameUpdateLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerAddressUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                        .addComponent(customerAddressUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerEmailUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerEmailUpdateLabel))
                .addGap(18, 18, 18)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateCustomerButtonFinal)
                    .addComponent(notificationCustomerUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteCustomerButton)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jLayeredPane1.add(updateCustomerPanel);
        updateCustomerPanel.setBounds(0, 0, 730, 340);

        customerIDShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerIDShippingUpdateLabel.setText("Customer ID:");

        currentCityShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        currentCityShippingUpdateLabel.setText("Current City:");

        shippingDateShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        shippingDateShippingUpdateLabel.setText("Shipping Date:");

        updateShippingButtonFinal.setText("UPDATE");
        updateShippingButtonFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShippingButtonFinalActionPerformed(evt);
            }
        });

        invalidShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        invalidShippingUpdateLabel.setForeground(new java.awt.Color(153, 0, 0));

        arrivalDateShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        arrivalDateShippingUpdateLabel.setText("Arrival Date:");

        javax.swing.GroupLayout updateShipmentPanelLayout = new javax.swing.GroupLayout(updateShipmentPanel);
        updateShipmentPanel.setLayout(updateShipmentPanelLayout);
        updateShipmentPanelLayout.setHorizontalGroup(
            updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateShipmentPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arrivalDateShippingUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shippingDateShippingUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(currentCityShippingUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerIDShippingUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerIDShippingUpdateField)
                    .addComponent(currentCityShippingUpdateField)
                    .addComponent(shippingDateShippingUpdateField)
                    .addGroup(updateShipmentPanelLayout.createSequentialGroup()
                        .addComponent(updateShippingButtonFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(invalidShippingUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(arrivalDateShippingUpdateField))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        updateShipmentPanelLayout.setVerticalGroup(
            updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateShipmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDShippingUpdateLabel)
                    .addComponent(customerIDShippingUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(currentCityShippingUpdateLabel)
                    .addComponent(currentCityShippingUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shippingDateShippingUpdateLabel)
                    .addComponent(shippingDateShippingUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrivalDateShippingUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalDateShippingUpdateLabel))
                .addGap(13, 13, 13)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateShippingButtonFinal)
                    .addComponent(invalidShippingUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLayeredPane1.add(updateShipmentPanel);
        updateShipmentPanel.setBounds(0, 0, 730, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newShipmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateShipmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewCustomerTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(viewInventoryTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(viewShipmentTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newShipmentButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateInventoryButton)
                        .addComponent(updateCustomerButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateShipmentButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewInventoryTableButton)
                        .addComponent(viewShipmentTableButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewCustomerTableButton)
                    .addComponent(logOutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newShipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newShipmentButtonActionPerformed
        newOrderPanel.setVisible(true);
        updateInventoryPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_newShipmentButtonActionPerformed

    private void updateInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInventoryButtonActionPerformed
        newOrderPanel.setVisible(false);
        updateInventoryPanel.setVisible(true);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_updateInventoryButtonActionPerformed

    private void updateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonActionPerformed
        newOrderPanel.setVisible(false);
        updateInventoryPanel.setVisible(false);
        updateCustomerPanel.setVisible(true);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_updateCustomerButtonActionPerformed

    private void updateShipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShipmentButtonActionPerformed
        newOrderPanel.setVisible(false);
        updateInventoryPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_updateShipmentButtonActionPerformed

    private void viewInventoryTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInventoryTableButtonActionPerformed
        Inventory frame = new Inventory();
        frame.pack();
        frame.setVisible(true);
        newOrderPanel.setVisible(false);
        updateInventoryPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_viewInventoryTableButtonActionPerformed

    private void viewShipmentTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewShipmentTableButtonActionPerformed
        Shipment frame = new Shipment();
        frame.pack();
        frame.setVisible(true);
        newOrderPanel.setVisible(false);
        updateInventoryPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_viewShipmentTableButtonActionPerformed

    private void viewCustomerTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerTableButtonActionPerformed
        Customer frame = new Customer();
        frame.pack();
        frame.setVisible(true);
        newOrderPanel.setVisible(false);
        updateInventoryPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_viewCustomerTableButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
        //code to check all fields are valid
        
        //if all fields are not valid, display error message to employee
        //notificationLabel.setText("INVALID DATA! TRY AGAIN!");
        
        //code to submit all data to the database
        
        
        
        //clear all fields after data was successfully submitted
        customerNameField.setText("");
        customerIDField.setText("");
        customerAddressField.setText("");
        customerEmailField.setText("");
        itemIDField.setText("");
        destinationField.setText("");
        itemWeightField.setText("");
        itemCountField.setText("");
        shipmentIDField.setText("");
        //display notification to the employee that data was successfully submitted
        notificationLabel.setText("SUCCESSFULLY SUBMITTED!");
    }//GEN-LAST:event_submitButtonActionPerformed

    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonActionPerformed
        //clear all fields
        customerNameField.setText("");
        customerIDField.setText("");
        customerAddressField.setText("");
        customerEmailField.setText("");
        itemIDField.setText("");
        destinationField.setText("");
        itemWeightField.setText("");
        itemCountField.setText("");
        shipmentIDField.setText("");
        //display notification to the employee that all fields are cleared
        notificationLabel.setText("ALL FIELDS CLEARED!");
    }//GEN-LAST:event_clearAllButtonActionPerformed

    private void updateInventoryButtonFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInventoryButtonFinalActionPerformed
       
    }//GEN-LAST:event_updateInventoryButtonFinalActionPerformed

    private void deleteInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInventoryButtonActionPerformed
        
    }//GEN-LAST:event_deleteInventoryButtonActionPerformed

    private void updateCustomerButtonFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonFinalActionPerformed
        //code to check all fields are valid
        
        //if all fields are not valid, display error message to employee
        //notificationCustomerUpdateLabel.setText("INVALID DATA! TRY AGAIN!");
        
        //code to submit updated data to the database
        
        //clear fields and disable fields/buttons
        customerNameUpdateField.setText("");
        customerAddressUpdateField.setText("");
        customerEmailUpdateField.setText("");
        customerNameUpdateField.setEnabled(false);
        customerAddressUpdateField.setEnabled(false);
        customerEmailUpdateField.setEnabled(false);
        updateCustomerButtonFinal.setEnabled(false);
        deleteCustomerButton.setEnabled(false);
        //display notification to the employee that data was successfully updated
        notificationCustomerUpdateLabel.setText("SUCCESSFULLY UPDATED!");
    }//GEN-LAST:event_updateCustomerButtonFinalActionPerformed

    private void updateShippingButtonFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShippingButtonFinalActionPerformed
       
    }//GEN-LAST:event_updateShippingButtonFinalActionPerformed

    private void searchUpdateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUpdateCustomerButtonActionPerformed
        //code to check search field is valid
        
        //if search field is not valid, display error message to employee
        //notificationCustomerUpdateLabel.setText("INVALID DATA! TRY AGAIN!");
        
        
        //if search field is valid, enable and populate associated fields/buttons to update information
        customerNameUpdateField.setEnabled(true);
        customerAddressUpdateField.setEnabled(true);
        customerEmailUpdateField.setEnabled(true);
        updateCustomerButtonFinal.setEnabled(true);
        deleteCustomerButton.setEnabled(true);
    }//GEN-LAST:event_searchUpdateCustomerButtonActionPerformed

    private void deleteCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerButtonActionPerformed
        //code to check all fields are valid
        
        //if all fields are not valid, display error message to employee
        //notificationCustomerUpdateLabel.setText("INVALID DATA! TRY AGAIN!");
        
        //if all fields are valid, code to delete data from the database
        
        //clear fields and disable fields/buttons
        customerNameUpdateField.setText("");
        customerAddressUpdateField.setText("");
        customerEmailUpdateField.setText("");
        customerNameUpdateField.setEnabled(false);
        customerAddressUpdateField.setEnabled(false);
        customerEmailUpdateField.setEnabled(false);
        updateCustomerButtonFinal.setEnabled(false);
        deleteCustomerButton.setEnabled(false);
        //display notification to the employee that data was successfully deleted
        notificationCustomerUpdateLabel.setText("SUCCESSFULLY DELETED!");
    }//GEN-LAST:event_deleteCustomerButtonActionPerformed

    private void searchInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInventoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInventoryButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalDateShippingUpdateField;
    private javax.swing.JLabel arrivalDateShippingUpdateLabel;
    private javax.swing.JButton clearAllButton;
    private javax.swing.JTextField currentCityShippingUpdateField;
    private javax.swing.JLabel currentCityShippingUpdateLabel;
    private javax.swing.JLabel customerAddressButton;
    private javax.swing.JTextField customerAddressField;
    private javax.swing.JTextField customerAddressUpdateField;
    private javax.swing.JLabel customerAddressUpdateLabel;
    private javax.swing.JTextField customerEmailField;
    private javax.swing.JLabel customerEmailLabel;
    private javax.swing.JTextField customerEmailUpdateField;
    private javax.swing.JLabel customerEmailUpdateLabel;
    private javax.swing.JTextField customerIDCustomerUpdateField;
    private javax.swing.JLabel customerIDCustomerUpdateLabel;
    private javax.swing.JTextField customerIDField;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JTextField customerIDShippingUpdateField;
    private javax.swing.JLabel customerIDShippingUpdateLabel;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameUpdateField;
    private javax.swing.JLabel customerNameUpdateLabel;
    private javax.swing.JButton deleteCustomerButton;
    private javax.swing.JButton deleteInventoryButton;
    private javax.swing.JTextField destinationField;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JLabel invalidShippingUpdateLabel;
    private javax.swing.JLabel itemCountButton;
    private javax.swing.JTextField itemCountField;
    private javax.swing.JTextField itemDescriptionUpdateField;
    private javax.swing.JLabel itemDescriptionUpdateLabel;
    private javax.swing.JLabel itemIDButton;
    private javax.swing.JTextField itemIDField;
    private javax.swing.JTextField itemIDUpdateField;
    private javax.swing.JLabel itemIDUpdateLabel;
    private javax.swing.JTextField itemStockLevelUpdateField;
    private javax.swing.JLabel itemStockLevelUpdateLabel;
    private javax.swing.JLabel itemWeightButton;
    private javax.swing.JTextField itemWeightField;
    private javax.swing.JTextField itemWeightUpdateField;
    private javax.swing.JLabel itemWeightUpdateLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel newOrderPanel;
    private javax.swing.JButton newShipmentButton;
    private javax.swing.JLabel notificationCustomerUpdateLabel;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JLabel notificationUpdateInventoryLabel;
    private javax.swing.JButton searchInventoryButton;
    private javax.swing.JButton searchUpdateCustomerButton;
    private javax.swing.JTextField shipmentIDField;
    private javax.swing.JLabel shipmentIDLabel;
    private javax.swing.JTextField shippingDateShippingUpdateField;
    private javax.swing.JLabel shippingDateShippingUpdateLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton updateCustomerButton;
    private javax.swing.JButton updateCustomerButtonFinal;
    private javax.swing.JPanel updateCustomerPanel;
    private javax.swing.JButton updateInventoryButton;
    private javax.swing.JButton updateInventoryButtonFinal;
    private javax.swing.JPanel updateInventoryPanel;
    private javax.swing.JButton updateShipmentButton;
    private javax.swing.JPanel updateShipmentPanel;
    private javax.swing.JButton updateShippingButtonFinal;
    private javax.swing.JButton viewCustomerTableButton;
    private javax.swing.JButton viewInventoryTableButton;
    private javax.swing.JButton viewShipmentTableButton;
    // End of variables declaration//GEN-END:variables
}
