/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package taproim_cmsc495;

import java.awt.Color;

/**
 *
 * @author Brandon
 */
public class Display_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Display_GUI
     */
    public Display_GUI() {
        this.setTitle("                               "
                + "                                         "
                + "                      TAPRO-IM SYSTEMS");
        //getContentPane().setBackground(Color.GRAY);
        initComponents();
        newOrderPanel.setVisible(false);
        searchCustomerPanel.setVisible(false);
        updateOrderPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newOrderButton = new javax.swing.JButton();
        updateCustomerButton = new javax.swing.JButton();
        updateOrderButton = new javax.swing.JButton();
        updateShipmentButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tableLabel = new javax.swing.JLabel();
        viewInventoryTableButton = new javax.swing.JButton();
        viewShipmentTableButton = new javax.swing.JButton();
        viewCustomerTableButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        newOrderPanel = new javax.swing.JPanel();
        customerNameLabel = new javax.swing.JLabel();
        customerNameField = new javax.swing.JTextField();
        customerIDLabel = new javax.swing.JLabel();
        customerIDField = new javax.swing.JTextField();
        customerAddressButton = new javax.swing.JLabel();
        customerAddressField = new javax.swing.JTextField();
        itemIDButton = new javax.swing.JLabel();
        itemIDField = new javax.swing.JTextField();
        itemCountButton = new javax.swing.JLabel();
        itemCountField = new javax.swing.JTextField();
        itemWeightButton = new javax.swing.JLabel();
        itemWeightField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        clearAllButton = new javax.swing.JButton();
        invalidLabel = new javax.swing.JLabel();
        searchCustomerPanel = new javax.swing.JPanel();
        customerIDSearchLabel = new javax.swing.JLabel();
        customerIDSearchField = new javax.swing.JTextField();
        orderSearchButton = new javax.swing.JButton();
        invalidCustomerIDLabel = new javax.swing.JLabel();
        shipmentSearchButton = new javax.swing.JButton();
        customerInfoSearchButton = new javax.swing.JButton();
        updateOrderPanel = new javax.swing.JPanel();
        customerIDOrderUpdateLabel = new javax.swing.JLabel();
        itemIDUpdateLabel = new javax.swing.JLabel();
        itemCountUpdateLabel = new javax.swing.JLabel();
        itemWeightUpdateLabel = new javax.swing.JLabel();
        customerIDOrderUpdateField = new javax.swing.JTextField();
        itemIDUpdateField = new javax.swing.JTextField();
        itemCountUpdateField = new javax.swing.JTextField();
        itemWeightUpdateField = new javax.swing.JTextField();
        updateButtonFinal = new javax.swing.JButton();
        cancelOrderButtonFinal = new javax.swing.JButton();
        invalidUpdateOrderLabel = new javax.swing.JLabel();
        updateCustomerPanel = new javax.swing.JPanel();
        customerIDCustomerUpdateLabel = new javax.swing.JLabel();
        customerIDCustomerUpdateField = new javax.swing.JTextField();
        customerNameUpdateLabel = new javax.swing.JLabel();
        customerAddressUpdateLabel = new javax.swing.JLabel();
        customerNameUpdateField = new javax.swing.JTextField();
        customerAddressUpdateField = new javax.swing.JTextField();
        updateCustomerButtonFinal = new javax.swing.JButton();
        invalidCustomerUpdateLabel = new javax.swing.JLabel();
        updateShipmentPanel = new javax.swing.JPanel();
        customerIDShippingUpdateLabel = new javax.swing.JLabel();
        customerIDShippingUpdateField = new javax.swing.JTextField();
        currentCityShippingUpdateLabel = new javax.swing.JLabel();
        currentCityShippingUpdateField = new javax.swing.JTextField();
        shippingDateShippingUpdateLabel = new javax.swing.JLabel();
        shippingDateShippingUpdateField = new javax.swing.JTextField();
        updateShippingButtonFinal = new javax.swing.JButton();
        invalidShippingUpdateLabel = new javax.swing.JLabel();
        arrivalDateShippingUpdateLabel = new javax.swing.JLabel();
        arrivalDateShippingUpdateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newOrderButton.setText("NEW ORDER");
        newOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrderButtonActionPerformed(evt);
            }
        });

        updateCustomerButton.setText("UPDATE CUSTOMER");
        updateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonActionPerformed(evt);
            }
        });

        updateOrderButton.setText("UPDATE/CANCEL ORDER");
        updateOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrderButtonActionPerformed(evt);
            }
        });

        updateShipmentButton.setText("UPDATE SHIPMENT");
        updateShipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShipmentButtonActionPerformed(evt);
            }
        });

        tablePanel.setBackground(new java.awt.Color(204, 204, 204));
        tablePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        tableLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tableLabel.setText("      TABLE DISPLAY");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(tableLabel)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        viewInventoryTableButton.setText("VIEW INVENTORY TABLE");
        viewInventoryTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInventoryTableButtonActionPerformed(evt);
            }
        });

        viewShipmentTableButton.setText("VIEW SHIPMENT TABLE");
        viewShipmentTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewShipmentTableButtonActionPerformed(evt);
            }
        });

        viewCustomerTableButton.setText("VIEW CUSTOMER TABLE");
        viewCustomerTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerTableButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("LOG OUT");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        newOrderPanel.setEnabled(false);

        customerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerNameLabel.setText("Customer Name:");

        customerIDLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerIDLabel.setText("Customer ID:");

        customerAddressButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerAddressButton.setText("Customer Address:");

        itemIDButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemIDButton.setText("Item ID Number:");

        itemCountButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemCountButton.setText("Item Count:");

        itemWeightButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemWeightButton.setText("Item Weight:");

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        clearAllButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        clearAllButton.setText("CLEAR ALL");
        clearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newOrderPanelLayout = new javax.swing.GroupLayout(newOrderPanel);
        newOrderPanel.setLayout(newOrderPanelLayout);
        newOrderPanelLayout.setHorizontalGroup(
            newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(itemWeightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemIDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerAddressButton, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(customerIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newOrderPanelLayout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(invalidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addComponent(customerNameField)
                    .addComponent(customerIDField)
                    .addComponent(customerAddressField)
                    .addComponent(itemIDField)
                    .addComponent(itemCountField)
                    .addComponent(itemWeightField))
                .addContainerGap())
        );
        newOrderPanelLayout.setVerticalGroup(
            newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOrderPanelLayout.createSequentialGroup()
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerAddressButton)
                    .addComponent(customerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemIDButton)
                    .addComponent(itemIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemCountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemWeightButton)
                    .addGroup(newOrderPanelLayout.createSequentialGroup()
                        .addComponent(itemWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invalidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLayeredPane1.add(newOrderPanel);
        newOrderPanel.setBounds(10, 0, 710, 220);

        searchCustomerPanel.setEnabled(false);

        customerIDSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerIDSearchLabel.setText("Customer ID:");

        orderSearchButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        orderSearchButton.setText("Order Search");
        orderSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSearchButtonActionPerformed(evt);
            }
        });

        invalidCustomerIDLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        invalidCustomerIDLabel.setForeground(new java.awt.Color(153, 0, 0));

        shipmentSearchButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        shipmentSearchButton.setText("Shipment Search");
        shipmentSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipmentSearchButtonActionPerformed(evt);
            }
        });

        customerInfoSearchButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        customerInfoSearchButton.setText("Customer Search");
        customerInfoSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerInfoSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchCustomerPanelLayout = new javax.swing.GroupLayout(searchCustomerPanel);
        searchCustomerPanel.setLayout(searchCustomerPanelLayout);
        searchCustomerPanelLayout.setHorizontalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(customerIDSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerIDSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(invalidCustomerIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                            .addComponent(orderSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shipmentSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(customerInfoSearchButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchCustomerPanelLayout.setVerticalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerIDSearchLabel)
                    .addComponent(customerIDSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderSearchButton)
                        .addComponent(shipmentSearchButton))
                    .addComponent(customerInfoSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(invalidCustomerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 154, Short.MAX_VALUE))
        );

        jLayeredPane1.add(searchCustomerPanel);
        searchCustomerPanel.setBounds(0, 0, 730, 240);

        customerIDOrderUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerIDOrderUpdateLabel.setText("Customer ID:");

        itemIDUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemIDUpdateLabel.setText("Item ID:");

        itemCountUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemCountUpdateLabel.setText("Item Count:");

        itemWeightUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemWeightUpdateLabel.setText("Item Weight:");

        itemCountUpdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCountUpdateFieldActionPerformed(evt);
            }
        });

        updateButtonFinal.setText("UPDATE");
        updateButtonFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonFinalActionPerformed(evt);
            }
        });

        cancelOrderButtonFinal.setText("CANCEL ORDER");
        cancelOrderButtonFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOrderButtonFinalActionPerformed(evt);
            }
        });

        invalidUpdateOrderLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        invalidUpdateOrderLabel.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout updateOrderPanelLayout = new javax.swing.GroupLayout(updateOrderPanel);
        updateOrderPanel.setLayout(updateOrderPanelLayout);
        updateOrderPanelLayout.setHorizontalGroup(
            updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateOrderPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerIDOrderUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(itemIDUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCountUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemWeightUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerIDOrderUpdateField)
                    .addComponent(itemIDUpdateField)
                    .addComponent(itemCountUpdateField)
                    .addComponent(itemWeightUpdateField)
                    .addGroup(updateOrderPanelLayout.createSequentialGroup()
                        .addGroup(updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(invalidUpdateOrderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(updateOrderPanelLayout.createSequentialGroup()
                                .addComponent(updateButtonFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelOrderButtonFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        updateOrderPanelLayout.setVerticalGroup(
            updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerIDOrderUpdateLabel)
                    .addComponent(customerIDOrderUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemIDUpdateLabel)
                    .addComponent(itemIDUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemCountUpdateLabel)
                    .addComponent(itemCountUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemWeightUpdateLabel)
                    .addComponent(itemWeightUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButtonFinal)
                    .addComponent(cancelOrderButtonFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidUpdateOrderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLayeredPane1.add(updateOrderPanel);
        updateOrderPanel.setBounds(0, 0, 730, 240);

        customerIDCustomerUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerIDCustomerUpdateLabel.setText("Customer ID:");

        customerNameUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerNameUpdateLabel.setText("Customer Name:");

        customerAddressUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerAddressUpdateLabel.setText("Customer Address:");

        customerNameUpdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameUpdateFieldActionPerformed(evt);
            }
        });

        updateCustomerButtonFinal.setText("UPDATE");
        updateCustomerButtonFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateCustomerPanelLayout = new javax.swing.GroupLayout(updateCustomerPanel);
        updateCustomerPanel.setLayout(updateCustomerPanelLayout);
        updateCustomerPanelLayout.setHorizontalGroup(
            updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerAddressUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(customerNameUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerIDCustomerUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerIDCustomerUpdateField)
                    .addComponent(customerNameUpdateField)
                    .addComponent(customerAddressUpdateField)
                    .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                        .addComponent(updateCustomerButtonFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(invalidCustomerUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        updateCustomerPanelLayout.setVerticalGroup(
            updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDCustomerUpdateLabel)
                    .addComponent(customerIDCustomerUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameUpdateLabel)
                    .addComponent(customerNameUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerAddressUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerAddressUpdateLabel))
                .addGap(18, 18, 18)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCustomerButtonFinal)
                    .addComponent(invalidCustomerUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jLayeredPane1.add(updateCustomerPanel);
        updateCustomerPanel.setBounds(0, 0, 730, 240);

        customerIDShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerIDShippingUpdateLabel.setText("Customer ID:");

        currentCityShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        currentCityShippingUpdateLabel.setText("Current City:");

        shippingDateShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        shippingDateShippingUpdateLabel.setText("Shipping Date:");

        updateShippingButtonFinal.setText("UPDATE");
        updateShippingButtonFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShippingButtonFinalActionPerformed(evt);
            }
        });

        invalidShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        invalidShippingUpdateLabel.setForeground(new java.awt.Color(153, 0, 0));

        arrivalDateShippingUpdateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        arrivalDateShippingUpdateLabel.setText("Arrival Date:");

        javax.swing.GroupLayout updateShipmentPanelLayout = new javax.swing.GroupLayout(updateShipmentPanel);
        updateShipmentPanel.setLayout(updateShipmentPanelLayout);
        updateShipmentPanelLayout.setHorizontalGroup(
            updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateShipmentPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arrivalDateShippingUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shippingDateShippingUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(currentCityShippingUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerIDShippingUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerIDShippingUpdateField)
                    .addComponent(currentCityShippingUpdateField)
                    .addComponent(shippingDateShippingUpdateField)
                    .addGroup(updateShipmentPanelLayout.createSequentialGroup()
                        .addComponent(updateShippingButtonFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(invalidShippingUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(arrivalDateShippingUpdateField))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        updateShipmentPanelLayout.setVerticalGroup(
            updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateShipmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDShippingUpdateLabel)
                    .addComponent(customerIDShippingUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(currentCityShippingUpdateLabel)
                    .addComponent(currentCityShippingUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shippingDateShippingUpdateLabel)
                    .addComponent(shippingDateShippingUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrivalDateShippingUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalDateShippingUpdateLabel))
                .addGap(13, 13, 13)
                .addGroup(updateShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateShippingButtonFinal)
                    .addComponent(invalidShippingUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLayeredPane1.add(updateShipmentPanel);
        updateShipmentPanel.setBounds(0, 0, 730, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateShipmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewCustomerTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(viewInventoryTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(viewShipmentTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newOrderButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateOrderButton)
                        .addComponent(updateCustomerButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateShipmentButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewInventoryTableButton)
                        .addComponent(viewShipmentTableButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewCustomerTableButton)
                    .addComponent(logOutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderButtonActionPerformed
        newOrderPanel.setVisible(true);
        searchCustomerPanel.setVisible(false);
        updateOrderPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_newOrderButtonActionPerformed

    private void updateOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrderButtonActionPerformed
        newOrderPanel.setVisible(false);
        searchCustomerPanel.setVisible(true);
        updateOrderPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_updateOrderButtonActionPerformed

    private void updateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonActionPerformed
        newOrderPanel.setVisible(false);
        searchCustomerPanel.setVisible(true);
        updateOrderPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_updateCustomerButtonActionPerformed

    private void updateShipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShipmentButtonActionPerformed
        newOrderPanel.setVisible(false);
        searchCustomerPanel.setVisible(true);
        updateOrderPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_updateShipmentButtonActionPerformed

    private void viewInventoryTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInventoryTableButtonActionPerformed
        Inventory frame = new Inventory();
        frame.pack();
        frame.setVisible(true);
        newOrderPanel.setVisible(false);
        searchCustomerPanel.setVisible(false);
        updateOrderPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_viewInventoryTableButtonActionPerformed

    private void viewShipmentTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewShipmentTableButtonActionPerformed
        Shipment frame = new Shipment();
        frame.pack();
        frame.setVisible(true);
        newOrderPanel.setVisible(false);
        searchCustomerPanel.setVisible(false);
        updateOrderPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_viewShipmentTableButtonActionPerformed

    private void viewCustomerTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerTableButtonActionPerformed
        Customer frame = new Customer();
        frame.pack();
        frame.setVisible(true);
        newOrderPanel.setVisible(false);
        searchCustomerPanel.setVisible(false);
        updateOrderPanel.setVisible(false);
        updateCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(false);
    }//GEN-LAST:event_viewCustomerTableButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void orderSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSearchButtonActionPerformed
        searchCustomerPanel.setVisible(false);
        updateOrderPanel.setVisible(true);
    }//GEN-LAST:event_orderSearchButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonActionPerformed
        
    }//GEN-LAST:event_clearAllButtonActionPerformed

    private void shipmentSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipmentSearchButtonActionPerformed
        searchCustomerPanel.setVisible(false);
        updateShipmentPanel.setVisible(true);
    }//GEN-LAST:event_shipmentSearchButtonActionPerformed

    private void customerInfoSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerInfoSearchButtonActionPerformed
        searchCustomerPanel.setVisible(false);
        updateCustomerPanel.setVisible(true);
    }//GEN-LAST:event_customerInfoSearchButtonActionPerformed

    private void itemCountUpdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCountUpdateFieldActionPerformed
        
    }//GEN-LAST:event_itemCountUpdateFieldActionPerformed

    private void updateButtonFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonFinalActionPerformed
       
    }//GEN-LAST:event_updateButtonFinalActionPerformed

    private void cancelOrderButtonFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOrderButtonFinalActionPerformed
        
    }//GEN-LAST:event_cancelOrderButtonFinalActionPerformed

    private void customerNameUpdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameUpdateFieldActionPerformed
        
    }//GEN-LAST:event_customerNameUpdateFieldActionPerformed

    private void updateCustomerButtonFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonFinalActionPerformed
        
    }//GEN-LAST:event_updateCustomerButtonFinalActionPerformed

    private void updateShippingButtonFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShippingButtonFinalActionPerformed
       
    }//GEN-LAST:event_updateShippingButtonFinalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalDateShippingUpdateField;
    private javax.swing.JLabel arrivalDateShippingUpdateLabel;
    private javax.swing.JButton cancelOrderButtonFinal;
    private javax.swing.JButton clearAllButton;
    private javax.swing.JTextField currentCityShippingUpdateField;
    private javax.swing.JLabel currentCityShippingUpdateLabel;
    private javax.swing.JLabel customerAddressButton;
    private javax.swing.JTextField customerAddressField;
    private javax.swing.JTextField customerAddressUpdateField;
    private javax.swing.JLabel customerAddressUpdateLabel;
    private javax.swing.JTextField customerIDCustomerUpdateField;
    private javax.swing.JLabel customerIDCustomerUpdateLabel;
    private javax.swing.JTextField customerIDField;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JTextField customerIDOrderUpdateField;
    private javax.swing.JLabel customerIDOrderUpdateLabel;
    private javax.swing.JTextField customerIDSearchField;
    private javax.swing.JLabel customerIDSearchLabel;
    private javax.swing.JTextField customerIDShippingUpdateField;
    private javax.swing.JLabel customerIDShippingUpdateLabel;
    private javax.swing.JButton customerInfoSearchButton;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameUpdateField;
    private javax.swing.JLabel customerNameUpdateLabel;
    private javax.swing.JLabel invalidCustomerIDLabel;
    private javax.swing.JLabel invalidCustomerUpdateLabel;
    private javax.swing.JLabel invalidLabel;
    private javax.swing.JLabel invalidShippingUpdateLabel;
    private javax.swing.JLabel invalidUpdateOrderLabel;
    private javax.swing.JLabel itemCountButton;
    private javax.swing.JTextField itemCountField;
    private javax.swing.JTextField itemCountUpdateField;
    private javax.swing.JLabel itemCountUpdateLabel;
    private javax.swing.JLabel itemIDButton;
    private javax.swing.JTextField itemIDField;
    private javax.swing.JTextField itemIDUpdateField;
    private javax.swing.JLabel itemIDUpdateLabel;
    private javax.swing.JLabel itemWeightButton;
    private javax.swing.JTextField itemWeightField;
    private javax.swing.JTextField itemWeightUpdateField;
    private javax.swing.JLabel itemWeightUpdateLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton newOrderButton;
    private javax.swing.JPanel newOrderPanel;
    private javax.swing.JButton orderSearchButton;
    private javax.swing.JPanel searchCustomerPanel;
    private javax.swing.JButton shipmentSearchButton;
    private javax.swing.JTextField shippingDateShippingUpdateField;
    private javax.swing.JLabel shippingDateShippingUpdateLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton updateButtonFinal;
    private javax.swing.JButton updateCustomerButton;
    private javax.swing.JButton updateCustomerButtonFinal;
    private javax.swing.JPanel updateCustomerPanel;
    private javax.swing.JButton updateOrderButton;
    private javax.swing.JPanel updateOrderPanel;
    private javax.swing.JButton updateShipmentButton;
    private javax.swing.JPanel updateShipmentPanel;
    private javax.swing.JButton updateShippingButtonFinal;
    private javax.swing.JButton viewCustomerTableButton;
    private javax.swing.JButton viewInventoryTableButton;
    private javax.swing.JButton viewShipmentTableButton;
    // End of variables declaration//GEN-END:variables
}
